### ISSUE TITLE
Weird crash affecting only some people

### ISSUE THREAD

**Issue by Rafii2198** [IMB11/Flow#11]
I am the creator of the Wynnic Enchantments modpack. After my latest 0.6.4 update, I am getting reports of this mod crashing the game.
The weird part is that only some people are crashing, not everyone, and I have no idea why.
A crash report from a user can be found in the issue from my repository https://github.com/Rafii2198/WynnicEnchantments/issues/7#issuecomment-1846229509

I personally am not affected by the crash and I have no idea what to do. It seems like mod incompatibility, but I can't check that personally.

**Comment by Rafii2198** [comment]
Well I don't have logs, as I said the crash is affecting only some people, and it doesn't affect me, I linked a comment for someone else's logs in hopes they will provide more information than I have.
I reported it because I really like the mod and it crashing means that I would have to remove it from the modpack which I don't want to do.

**Comment by IMB11** [comment]
> I cannot guarantee that my mods will work with the Quilt Loader. If you are using the Quilt Loader, please do not report any bugs to me. I will not be able to help you.

This seems to be a conflict with access wideners between dynamic FPS and Flow due to quilt. Can't do anything sorry. Use Fabric since this is a Fabric mod, not a quilt one.
