### ISSUE TITLE
[BUG] Conflict with PackedUp, menu cannot be closed anymore

### ISSUE THREAD

**Issue by DZAladan** [IMB11/Flow#13]
Note: this is a near [copypaste](https://github.com/SuperMartijn642/PackedUp/issues/68) from the PackedUp issues request, since this appears an issue on your end according to the dev.

I'll reiterate what I said there.

I'm running Flow version 1.4.0 on Minecraft 1.20.4 (Fabric)

There's a conflict with the mod PackedUp (https://modrinth.com/mod/packed-up-backpacks) where, if the backpack menu is opened, it won't close anymore no matter what key is pressed, forcing the player to close the game entirely.

However, I do not expect this to be fixed, but I thought it was necessary warning people in case they were to encounter the same issue like me and don't know how to solve it.

To reproduce the bug, install Packed Up 1.0.30c 1.4.0, and open the backpack in any way (keybind or right-click).

**Comment by IMB11** [comment]
This should be fixed in the next update.

**Comment by IMB11** [comment]
Should be fixed in 1.6.0
