### ISSUE TITLE
Incompatible with Sophisticated Storage & Backpack (cannot close UI)

### ISSUE THREAD

**Issue by hiimrickross** [IMB11/Flow#15]
There is no crash log as the game doesn't crash but there is just no functionality.

For example, normal storages -> plays the selected animation for opening and closing no problem.

But in the same world/instance, accessing a Sophisticated Storage/Backpack container, it will not play the animation and more importantly you cannot exit out of the container anymore with ESC, must go into the FTB Quests UI and then can exit out.

Sophisticated Core, Storage, Backpacks + Flow (Fabric).

**Comment by IMB11** [comment]
Should be fixed in the next update.
