### ISSUE TITLE
Incompatible with Wynntils

### ISSUE THREAD

**Issue by TeamBattino** [IMB11/Flow#16]
When using Flow in combination with [Wynntils](https://modrinth.com/mod/wynntils), and you attempt to join a server, it crashes as soon as you're passed the loading screen.

This is combination is also what caused the crashes here: #11  

Here's a screenshot from my mods folder:
![image](https://github.com/IMB11/Flow/assets/60046498/0e7bdb3d-ab35-4df6-96c9-b358157cdf42)

Here are my crash logs: https://mclo.gs/jITRI6G

**Comment by Rafii2198** [comment]
I also want to add that my modpack is not on Quilt, dunno why original issue was closed for Quilt, as the modpack never was on Quilt and probably never will be. And again this weirdly affects only some people, I, for one, do not experience it as well as multiple other people.

**Comment by IMB11** [comment]
Might be fixed in 1.6.0

**Comment by EngurRuzgar** [comment]
> Might be fixed in 1.6.0

@IMB11 Wynntills and Flow 1.6.0 won't be able to be tested because of the support for 1.20.2 being dropped.
