### ISSUE TITLE
Flow 1.5.0 - incompatibility with Blur mod and disable animation option isnt working

### ISSUE THREAD

**Issue by peow** [IMB11/Flow#18]
The Blur mod (https://modrinth.com/mod/blur-fabric) has some extra features, such as being able to add color gradients when you have your inventory open, however this is suppressed when using it together with Flow, as the Flow mod either removes all Background Tint, or adds its own Tint effect, it would be interesting if there was a "Default" option, where basically the Flow mod would not interfere and this feature would be disabled

*(Gradient Effect with Blur mod)*
![2024-03-29_18 44 41](https://github.com/IMB11/Flow/assets/105888751/508f2d64-7f05-422c-8a01-b542ec64306c)

-------------

Another problem I found is the fact that the "Disable Ease Out" option is not working, the animation itself is disabled but the inventory remains locked after you close it, to reproduce this I recommend putting a high number in "Easing Duration", like for example 1000ms, this way when you close the inventory you still have to wait 1 second to be able to move, and this is a problem since the shortest possible time is 100ms, so you always have to wait to be able to move after close the inventory (the solution I found was to modify the configuration file, I put "easeOutDuration": 0.01," so the delay was only 10ms)

![image](https://github.com/IMB11/Flow/assets/105888751/28b9825d-5b5e-4fad-923c-f4bff4373fbc)

---------

if is possible to fix these problems i ask you to publish an update to **fabric 1.20.1**

**Comment by IMB11** [comment]
yeah, blur isn't going to be compatible unfortunately, however I do plan to add the majority of features it provides in with the next update which will add detailed bg animation options.

**Comment by IMB11** [comment]
Ill take a look at this timeout issue.

**Comment by Killercrab432** [comment]
i think im facing a similiar issue as stated above, after the 1.5.0 update my modpack that has easing out disabled has my EMI interface still ease out and my game will act like im in my inventory even after its close for about 0.5 seconds, very frustrating and will probably just use 1.4.0 for now

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
