### ISSUE TITLE
incompatibility with EMI

### ISSUE THREAD

**Issue by peow** [IMB11/Flow#22]
EMI is a item/recipe viewer, but Flow can't remove the background tint from the inventory when using EMI
![2024-04-27_13 36 22](https://github.com/IMB11/Flow/assets/105888751/cfd84222-6811-4fb7-ae6a-ae54eb754759)

and when activating the “Use Batched Renderer” option that optimizes EMI

![image](https://github.com/IMB11/Flow/assets/105888751/f03774ba-b856-427d-bf04-9ad0d7f3b245)

Flow's Expanded animations stop working correctly, and a toast saying so appears on the screen:
![2024-04-27_13 33 25](https://github.com/IMB11/Flow/assets/105888751/0e9d5a17-e85c-44a5-a523-c43b9578dbaa)

but with the “Use Batched Renderer” option disabled, EMI works correctly with Expanded animations - only the remove background tint doesn't work

im using Fabric 1.20.1, latest.log: https://mclo.gs/yxY9Tqe

**Comment by IMB11** [comment]
You need the batched renderer to be disabled for EMI to work with flow unfortunately.

**Comment by IMB11** [comment]
Thanks for the video, this will make it really easy to reproduce, i'll take a look later this week :+1:

**Comment by makumaku1974** [comment]
I think recipe tree is broken with EMI

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
