### ISSUE TITLE
incompatibility with Rechiseled

### ISSUE THREAD

**Issue by peow** [IMB11/Flow#26]
Rechiseled (https://modrinth.com/mod/rechiseled) add a Chisel that allows you to exchange between various decorative blocks

using the Chisel opens a screen, but when used together with Flow, this new screen cannot be closed, by pressing ESC or the E key you regain control of your character's view but the window remains open, and the only way to close it is by changing the Chisel slot in the hotbar

![2024-05-12_20 24 14](https://github.com/IMB11/Flow/assets/105888751/b36f5659-b0da-4b53-ab10-a7bd4c8db32c)
![2024-05-12_20 24 37](https://github.com/IMB11/Flow/assets/105888751/204f27af-94b4-4fd1-9968-cd07fcdd4528)

------------

this screen doesn't receive any animation, and the only way to use these 2 mods together is to disable Flow's Ease In and Ease Out.

![2024-05-12_20 28 47](https://github.com/IMB11/Flow/assets/105888751/c783d38d-d334-482c-a90f-4968921897d8)

I tried to block the **ScreenClassName** of Rechiseled in Flow but it didn't work, I tried the following:

	"disabledScreens": [
		"com.supermartijn642.rechiseled.screen.BaseChiselingContainerScreen",
		"com.supermartijn642.rechiseled.screen.ChiselContainer",
		"com.supermartijn642.rechiseled.screen.PreviewModeButtonWidget",
		"top.theillusivec4.curios.client.gui.CuriosScreen"
	],

but nothing has changed 
I'm only using the necessary mods 
![2024-05-12_20 33 55](https://github.com/IMB11/Flow/assets/105888751/aaf17853-231d-4966-b2da-10be5e1d87fb)

config file: https://gist.github.com/peow/28fe2fa49256097ff9ed16f3e379d942

---------------

if is possible to fix this please make a **1.20.1** update, thanks

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
