### ISSUE TITLE
Delay after closing interfaces

### ISSUE THREAD

**Issue by ovchvi** [IMB11/Flow#27]
When the inventory is closed during animation playing and a little longer, player cannot control character. This happens if you close the inventory (Esc) and THEN press any movement button (W, A, S, D). If you hold down the movement button when the inventory is open and then close it, there will be no such delay, just as if you hold down the button before opening the inventory. This problem really affects the gameplay. I have to get used to pressing the button in advance. There is no such delay while modification isn't installed. It happens on mod version 1.5.0 for 1.20.1. I really hope for a fix! Thank you.
https://imgur.com/WT8BXqV

**Comment by IMB11** [comment]
Wow. This was surprisingly easy to fix. Will be in the next update.

**Comment by ovchvi** [comment]
Nice, thank you! Will wait)
