### ISSUE TITLE
Freeze bug

### ISSUE THREAD

**Issue by hacyier** [IMB11/Flow#28]
When you spam **Right Mouse Button** on any utility block, in order to open the **GUI**, and spam **ESC** at the same time to close the menu, then a sudden freeze appears which freezes the whole pc or make it lag very bad. [VIDEO](https://youtu.be/WgCh8jj5IBA)

**Comment by IMB11** [comment]
This will be fixed in the next update.

**Comment by IMB11** [comment]
This might be fixed in 1.6.0, this is really your own fault though, lag occurs even in vanilla when spamming the GUI button.
