### ISSUE TITLE
[BUG] 1.21 Flow \\ Ease out animation is not working.

### ISSUE THREAD

**Issue by makumaku1974** [IMB11/Flow#33]
This is a 1.21 issue because ive recently run the mod today. Ease out animation wont work no matter how I restart the world or reset the game.

**Comment by IMB11** [comment]
This is a known issue, fixing as soon as i can!

**Comment by IMB11** [comment]
Should be fixed in the re-release.

**Comment by thisiskret** [comment]
Is it completed, Is it?

**Comment by makumaku1974** [comment]
> Is it completed, Is it?

this is fixed already.

**Comment by thisiskret** [comment]
> > Is it completed, Is it?
> 
> this is fixed already.

Nope, it isn't.

**Comment by makumaku1974** [comment]
> > > Is it completed, Is it?
> > 
> > 
> > this is fixed already.
> 
> Nope, it isn't.

are you on version 1.21? Have you tried deleting the config file for this mod?
