### ISSUE TITLE
Recipe Viewers disappearing during the Ease Out animation

### ISSUE THREAD

**Issue by peow** [IMB11/Flow#34]
when closing the inventory the items/recipe viewers don't follow the animation
I tested with both EMI and REI

https://github.com/IMB11/Flow/assets/105888751/2c7f143e-a126-4927-990f-bea685c5e7e1

Fabric 1.20.1, Flow 1.6.0

**Comment by EngurRuzgar** [comment]
#35

**Comment by IMB11** [comment]
This is intended, you either have movement during the transition out, or the recipe viewer being displayed, i will create an option to switch between the transition implementations at a later date.

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
