### ISSUE TITLE
Mod X is incompatible with Flow!

### ISSUE THREAD

**Issue by IMB11** [IMB11/Flow#35]
Mods can be incompatible with Flow for a various number of reasons.

Known incompatibilities:

- Blur
- Inventory Blur

Please comment any further incompatibles here.

**Comment by EngurRuzgar** [comment]
1.20.1 with REI works flawlessly for me, you might want to add a disclaimer

**Comment by tajemniktv** [comment]
Yeah, 1.21 REI latest (up to 04.06.24) doesn't work as it just doesn't show up
