### ISSUE TITLE
Compatibility with Travelers Backpack.

### ISSUE THREAD

**Issue by makumaku1974** [IMB11/Flow#36]
I have 3 mods installed: Traveler's Backpack, Flow, and Blur.

I dont know what causes this issue after right clicking with the backpack it does something weird.

So this is the first screenshot. As you can see, this was taken after opening the backpack.
![2024-07-02_14 16 30](https://github.com/IMB11/Flow/assets/129804277/612659a3-416f-444b-9ff4-45538e211bd3)

This one is closing the backpack. Leaving an Afterimage of the GUI.
![2024-07-02_14 16 37](https://github.com/IMB11/Flow/assets/129804277/a7de01e8-f149-4334-af1a-46b9894c3df3)

Final result leaving blur to the screen temporarily because it can be fixed by opening the crafting menu.
![2024-07-02_14 16 58](https://github.com/IMB11/Flow/assets/129804277/7e99e4f4-9ed5-442d-82ab-9996ff183776)

**Comment by EngurRuzgar** [comment]
This is most likely an issue with Blur as it's known to not be compatible with Flow.

**Comment by makumaku1974** [comment]
Wait. Does Flow already has a blur feature?

**Comment by EngurRuzgar** [comment]
I believe Flow 1.6.0 has but I am not sure as I have not tested it. Try removing Blur and check out the Flow config file.

**Comment by makumaku1974** [comment]
I will. But if there's none would you add a blur feature instead of the tint?

**Comment by makumaku1974** [comment]
![2024-07-02_14 31 49](https://github.com/IMB11/Flow/assets/129804277/4f57df05-0610-46d1-8306-f681217573a4)

**Comment by IMB11** [comment]
Flow already includes a blur functionality.

**Comment by makumaku1974** [comment]
> Flow already includes a blur functionality.

I see, by any chance will Traveler's Backpack be fixed?

**Comment by IMB11** [comment]
Yes, i will look into it.

**Comment by IMB11** [comment]
For now though, use the comparability config options to try resolve the issue yourself.

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
