### ISSUE TITLE
Disable Flow animation on "JEI"

### ISSUE THREAD

**Issue by ReapaxTTV** [IMB11/Flow#38]
I am currently using both the "Just Enough Items" and "Flow" mods in Minecraft.
And I noticed that the animation happens to the "Item List" (JEI) on the right too.

I would like to request a feature that allows users to disable animations from JEI
or if it is possible, let me know how to do it

Troubleshooting Steps Taken:
* I have attempted to modify settings by adding (mezz.jei.gui.overlay.IngredientListOverlay) in the "Disabled Screens" option, but this did not resolve the issue.
* I have also checked the JEI and Flow mod settings in-game but could not find an option to disable animations.

Additional Information:
Minecraft Version: 1.21
JEI Version: jei-1.21-fabric-19.0.0.11
Flow Mod Version: flow-1.6.1+1.21

**Comment by TheRedstoneShark** [comment]
I would also like to see this feature for EMI. When using my favorite animation type (expand), EMI popping out feels unnatural and weird.

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
