### ISSUE TITLE
Crash on closing inventory (1.6.1, 1.20.1)

### ISSUE THREAD

**Issue by ilia-21** [IMB11/Flow#43]
Hello! Thank you for making this amazing mod. 
I updated from 1.5.0 to 1.6.1 because I saw the input delay issue was fixed. Now my game crashes every time I close the inventory.
Minecraft log: https://paste.ee/p/3SBDF

**Comment by thisiskret** [comment]
Happens in other UI elements too, like closing the crafting table UI if the recipe book is open.

Fun sidenote- the developer refused to fix this crash on another issue filed solely because it occurs on Quilt. This is a widespread serious crash that needs to be fixed

**Comment by IMB11** [comment]
> Fun sidenote- the developer refused to fix this crash on another issue filed solely because it occurs on Quilt. This is a widespread serious crash that needs to be fixed

Fun sidenote- I'm maintaining over 15 projects here for 5 game versions, across 3 modloaders for some projects, I'm sorry if I'm not fixing bugs as soon as they occur, that's unrealistic.

I've put out a bug bounty on the Fabric Discord server which should hopefully encourage people to help me fix this issue

**Comment by ilia-21** [comment]
It's okay, I understand how hard it is to maintain this many projects. Take your time. Close this issue if needed

**Comment by IMB11** [comment]
This should be fixed in 2.0.0
