### ISSUE TITLE
Latest update broke trinket integration

### ISSUE THREAD

**Issue by SeoliteQ** [IMB11/Flow#48]
Trinket slots are no longer showing up in inventory after upgrading Flow to the latest version. Tested for confirmation in isolated test world with only trinket (jewelry) mods and flow installed.

**Comment by IMB11** [comment]
Trinkets isn't on Fabric? Upload your logs to mclo.gs please

**Comment by SeoliteQ** [comment]
Trinkets is on fabric. I'll create a new test instance tomorrow accordingly. 

https://modrinth.com/mod/trinkets

**Comment by SeoliteQ** [comment]
Apologies for the late reply, I got caught up with work. I tried this out today again on my testbench, but it appears that your latest update fixed it. Trinket slots can now be hovered over and selected again. When I switch back to Flow's 28 July 2024 version, I cannot see the trinket slots again.
