### ISSUE TITLE
Unlock the mouse while close animation is playing

### ISSUE THREAD

**Issue by KaspianDev** [IMB11/Flow#5]
Currently when you close the inventory your mouse movement is locked until the animation ends.
Making it unlocked instantly after starting closing the inventory would be more dynamic and helpful in certain situations.

**Comment by mineblock11** [comment]
Neat idea, ill pop it in the next update along with relevant configuration options.

**Comment by IMB11** [comment]
Released in 1.5.0

**Comment by IMB11** [comment]
read the changelog
