### ISSUE TITLE
Items move at different speeds in EMI menu

### ISSUE THREAD

**Issue by pvpincarnate** [IMB11/Flow#52]
When using EMI some items in the EMI menu move at different speeds than others and overlap each other.

![2024-08-09_23 33 05](https://github.com/user-attachments/assets/66628b2e-93df-49c8-b5b3-46c7881b150f)

**Comment by IMB11** [comment]
Please upload your logs and a video, a screenshot isn't helpful.

**Comment by pvpincarnate** [comment]
Sorry about that. Here's the logs and a video.

[Logs](https://github.com/user-attachments/files/16569914/latest.log)


https://github.com/user-attachments/assets/22fb030a-6d16-4bc2-8a02-1f2a69b27be6

**Comment by IMB11** [comment]
Can you upload your logs to mclo.gs?

**Comment by pvpincarnate** [comment]
https://mclo.gs/c8lqgmk

**Comment by pvpincarnate** [comment]
it happens when using the batched renderer on EMI.

**Comment by IMB11** [comment]
Hm, it might be because some items are batch rendered, some items (like potions) are not - not much i can do about this sorry.
