### ISSUE TITLE
Mod Breaking and not playing animations, also causing tooltips to not display

### ISSUE THREAD

**Issue by ItsEndae** [IMB11/Flow#53]
Sometimes the mod stops working and playing the animation which will then also cause tooltips of items to not display, this is happening to me on both multiplayer and single player worlds.

![image_2024-08-14_165106668](https://github.com/user-attachments/assets/23c4411c-96e6-415f-ad6c-9d34eb644c69)

![2024-08-14_16 53 04](https://github.com/user-attachments/assets/7bd5d0f6-62c2-4c66-a61e-f94d8c196cb8)

**Comment by IMB11** [comment]
Please upload your logs

**Comment by IMB11** [comment]
Identify which mod is causing the incompatibly by removing/disabling your mods 1 by 1.

**Comment by MJsLittleQuestionMark** [comment]
I have had this issue too - it happens when you alt tab out and ur in fullscreen. Hope this helps

**Comment by CherubicBoot** [comment]
can confirm this, it also happened to me when alt-tab in full screen when opening container.
