### ISSUE TITLE
Incompatibility with MRU 1.0.0

### ISSUE THREAD

**Issue by TechMasterApp** [IMB11/Flow#55]
The mod doesn't work with MRU 1.0.0 and requires an older version of MRU. I can't downgrade cuz I have 2 other mods that require MRU 1.0.0.

**Comment by LordEnder-Kitty** [comment]
I noticed this as well. The workaround is to just downgrade everything that requires it. 1.0.0 is fairly new, so most of the mods should have versions that work with versions below 1.0.0.
I would appreciate if Flow could update to use it though. I most likely will happen in a few days, maybe a week or two if I had to guess. If other stuff is already updated, this is surely gonna be updated soon.

**Comment by LordEnder-Kitty** [comment]
I'm dying. Bro literally just posted this update around when I wrote the last message here.
