### ISSUE TITLE
Alt-tab causes item tool-tips to dissapear until the game is restarted.

### ISSUE THREAD

**Issue by DrBiznes** [IMB11/Flow#58]
I was running flow in a big modpack for the server wynncraft, at first I assumed it was a compatibility issue with other mods but after removing everything but flow and the big common optimization mods the issue persists. It only seems to occur on certain items with big tooltips in the game. You have to alt-tab while hovering over one of these items or menu buttons with huge tool-tips for it to happen, and it doesn't happen every time. 

I've attached a video of it happening, I'm running in fullscreen mode with GUI scale 2.
Log: https://mclo.gs/529qXNn

https://github.com/user-attachments/assets/e70183f3-3d3f-489e-8e96-ca2d031c97f1

**Comment by freakish-yourmom** [comment]
this same thing is happening to me and i have almost no mods

**Comment by Samaze123** [comment]
I tested each of my mods to finally see that's Flow that causing the bug.

**Comment by UncookedBurrito** [comment]
Same thing happening here

**Comment by oceanst1** [comment]
I also found this problem, I hope you can fix this bug as soon as possible.

**Comment by IMB11** [comment]
I've managed to reproduce this, will put out an update soon :)

**Comment by RomanKnight** [comment]
> I've managed to reproduce this, will put out an update soon :)

Any update on this? I'm having the same issue

**Comment by IMB11** [comment]
Im still working on it :) Give me a few days

**Comment by cobaltlol2** [comment]
> Im still working on it :) Give me a few days

Will it be fixed any time soon?
