### ISSUE TITLE
mod braking in the latest version 

### ISSUE THREAD

**Issue by rinkeChillow** [IMB11/Flow#59]
i updated the flow mod to its latest version and it broke somehow

![ezgif-5-8f1bac667f](https://github.com/user-attachments/assets/8ee18220-4a0c-4e0d-b22d-27b1cf90e3b2)
 
can it be fixed ?

**Comment by IMB11** [comment]
Please upload your logs to mclo.gs

**Comment by rinkeChillow** [comment]
ok then ?

**Comment by rinkeChillow** [comment]
no mods are conflicting other than these two witch has no effect on ui what so ever 
![image](https://github.com/user-attachments/assets/7c875e67-2c6e-4e1a-9240-7a4cbb2b253f)
 
also i have the same mod list this problem started only when i updated the flow mod and when i go back to an older version everything seems to be fine

**Comment by IMB11** [comment]
I need you to give me the link haha 😅

**Comment by rinkeChillow** [comment]
https://mclo.gs/9gWR2se

and found this in an older log 
![image](https://github.com/user-attachments/assets/df41ab0b-fd6e-4a2d-b5a7-cce6d3d96a1b)
don't understand it myself to be honest

**Comment by IMB11** [comment]
Flow is not compatible with the Blur mod, you should remove the Blur mod as Flow already provides some of it's core features.

**Comment by rinkeChillow** [comment]
well i think im just going to go back to an older version or update blur and experiment , ill be contacting the blur mod developer as well, as for you , is there a possibility for mods working together in the future ?

**Comment by IMB11** [comment]
No, Flow breaks Blur because of how it works, which is why I provide basic blur functionality in Flow...
