### ISSUE TITLE
when switching tabs background become dimmer 

### ISSUE THREAD

**Issue by rinkeChillow** [IMB11/Flow#62]
its a compatibility issue with the inventory tabs mod , when switching tabs it gets darker 

![image](https://github.com/user-attachments/assets/eebd1b92-c93e-4854-a819-769b36f7e290)

![image](https://github.com/user-attachments/assets/26dc00ce-8ed2-4519-b05a-516bfe9d3570)

i think that's all

**Comment by IMB11** [comment]
Will be fixed in 2.2.0
