### ISSUE TITLE
EMI adds persistent background tint and breaks Flow config options 

### ISSUE THREAD

**Issue by Lush-Pages** [IMB11/Flow#64]
Weird background tint with EMI installed. It moves with Flow's animation rather than fading in and out. Tried changing Flow's blur strength and background tint options to see if it'd help but they also seem to be broken. Disabling EMI ingame doesn't fix it, but uninstalling it completely fixes the issue and allows Flow's config options to work. I ran the game with only Flow, MRU, and EMI installed to make sure there wasn't another mod causing it.

MRU Version: 1.0.2 - 1.20.1 - Fabric

Flow Version: 2.1.2 - 1.20.1 

EMI Version: 1.1.13 - 1.20.1 - Fabric

https://github.com/user-attachments/assets/afbac79c-403f-4bac-9112-b4e65a91de28

**Comment by IMB11** [comment]
As a workaround, just disable Flow's background stuff in the config screen. I wont be updating 1.20.1 anymore.

**Comment by aurorarissime** [comment]
> As a workaround, just disable Flow's background stuff in the config screen. I wont be updating 1.20.1 anymore.

This doesn't work, the tint stil applies. Any other way..?
