### ISSUE TITLE
Alt tabbing breaks legendary tooltips

### ISSUE THREAD

**Issue by Sk1nny18** [IMB11/Flow#66]
simple explanation, when legendary tooltips is installed and you have flow, alt tabbing breaks all tooltips and requires restart to fix

**Comment by EnderBoy9217** [comment]
This occurs with all tooltips, not just legendary tooltips

**Comment by cobaltlol2** [comment]
happens 2 me too, really frusterating

**Comment by IMB11** [comment]
Duplicate of #58
