### ISSUE TITLE
Incompatbility with Map Atlas

### ISSUE THREAD

**Issue by MrGreenTea** [IMB11/Flow#9]
When using this mod and opening the atlas from Map Atlases the player can't close the screen anymore.

See this issue on their side: https://github.com/Pepperoni-Jabroni/MapAtlases/issues/127

Is there anything you can do on this side?

**Comment by mineblock11** [comment]
As a workaround, you can add "Excluded Screens" in the compatibility section of the config tab.

**Comment by mineblock11** [comment]
Simply add `pepjebs.mapatlases.screen.ScreenClassNameHere` to the list

**Comment by MrGreenTea** [comment]
> Simply add `pepjebs.mapatlases.screen.ScreenClassNameHere` to the list

Alright, so I have to add the whole path to the class? I only tried the class name itself and that didn't help. Thanks for the workaround, I'll try it as soon as possible :)

**Comment by IMB11** [comment]
Should be fixed in the next update.

**Comment by IMB11** [comment]
Fixed in 1.6.0
